tools:
  - module: "tools.generation"
    type: "generation"  # Math operations as generation
    include: ["calculate", "sum_numbers", "multiply"]
  - module: "tools.multimodal"
    type: "multimodal"  # Weather might involve multimodal data
    include: "all"
  - module: "tools.classification"
    type: "classification"
    include: ["classify_image"]
  - module: "tools.segmentation"
    type: "segmentation"
    include: ["segment_image"]
  - module: "tools.detection"
    type: "detection"
    include: ["detect_objects"]
  - module: "tools.generation"
    type: "generation"
    include: ["generate_image"]
