from __future__ import annotations

TASK_CLASS_MAP = {
    "modality": [
        "AS-OCT",
        "Color fundus photography",
        "CT",
        "Corneal topography",
        "External eye photo",
        "Fundus autofluorescence",
        "Fluorescein angiography",
        "Indocyanine green angiography",
        "IOL Master",
        "Infrared",
        "MRI",
        "OCT",
        "OCTA",
        "Pentacam",
        "RetCam",
        "Scanning laser ophthalmoscopy",
        "Slit lamp",
        "Specular microscopy",
        "Ultra-wide field imaging",
        "Ocular ultrasound",
        "Visual field",
        "Xray",
        "Corneal confocal",
    ],
    "cfp_quality": [
        "Small Pupil Artifact",
        "Out of focus",
        "Possible Severe Cataract",
        "Optic Disc Incomplete",
        "Macula Region Incomplete",
        "Poor Image Quality",
        "Gradable",
    ],
    "laterality": ["OD", "OS"],
    "multidis": [
        " and neuroretinitis",
        " aneurysms",
        " vasculitis",
        "Behcet disease",
        "Best vitelliform macular dystrophy",
        "Bietti's crystalline dystrophy",
        "CMV retinitis",
        "Coat's disease",
        "Dalen\u2013Fuchs nodules",
        "Eales' disease",
        "HIV retinopathy",
        "Lyme disease",
        "Stargardt disease",
        "Terson Syndrome",
        "Vogt-Koyanagi-Harada disease",
        "Von Hippel-Lindau Syndrome",
        "X-Linked juvenile retinoschisis ",
        "abnormal",
        "active toxoplasmosis",
        "acute posterior multifocal placoid pigment epitheliopathy",
        "acute retinal necrosis",
        "adult-onset vitelliform macular dystrophy\u00a0",
        "age-related macular degeneration",
        "albinism",
        "aneurysm",
        "angioid streak",
        "anterior ischemic optic neuropathy",
        "arterial-venous nicking",
        "arteriosclerosis",
        "arteriovenous malformation",
        "arteriovenous shunts",
        "asteroid bodies",
        "asteroid hyalosis",
        "atrophy",
        "birdshot retinochoroidopathy",
        "bone spicules pigmentation",
        "branch retinal artery occlusion",
        "branch retinal vein occlusion",
        "branching vascular network",
        "bull's eye maculopathy",
        "candida endophthalmitis",
        "central areolar choroidal dystrophy",
        "central retinal artery occlusion",
        "central retinal vein occlusion",
        "central serous chorioretinopathy",
        "chloroquine toxicity",
        "chorioretinal atrophy",
        "chorioretinal dystrophy",
        "choroidal detachment",
        "choroidal folds",
        "choroidal hemangioma",
        "choroidal mass",
        "choroidal melanoma",
        "choroidal metastasis",
        "choroidal neoplasm",
        "choroidal neovascularization",
        "choroidal nevus",
        "choroidal osteoma",
        "choroidal rupture",
        "choroiditis",
        "chronic central retinal vein occlusion",
        "chronic central serous chorioretinopathy",
        "chronic retinal vein occlusion",
        "chronic toxoplasmosis",
        "cilioretinal artery occlusion",
        "combined hamartoma",
        "commotio retinae",
        "cone dystrophy",
        "cone-rod dystrophy",
        "congenital anomaly",
        "congenital chorioretinal coloboma",
        "congenital chorioretinopathy",
        "congenital choroideremia",
        "congenital coloboma",
        "congenital macular coloboma",
        "congenital optic disc coloboma",
        "congenital stationary night blindness",
        "congential optic disc abnormalities",
        "cotton-wool spot",
        "cystoid macular edema",
        "detachment",
        "diabetic retinopathy",
        "drusen",
        "dry age-related macular degeneration",
        "edema",
        "endophthalmitis",
        "epiretinal membrane",
        "exudate",
        "exudative retinal detachment",
        "familial exudative vitreoretinopathy",
        "fibroproliferation",
        "fibrovascular retinal pigment epithelial detachment",
        "fleck",
        "gas-tamponade",
        "geographic atrophy",
        "glaucoma",
        "gyrate atrophy",
        "hamartoma",
        "hard drusen",
        "hemorrhage",
        "high myopia",
        "hyperpigmentation",
        "hyperplastic retinal pigment epithelium",
        "hypertensive retinopathy",
        "hypertrophy of the RPE",
        "hypopigmentation",
        "idiopathic retinitis",
        "infarction",
        "intermediate uveitis",
        "intraocular foreign body",
        "intraretinal hemorrhage",
        "intraretinal microvascular abnormalities",
        "ischemia",
        "ischemic branch retinal vein occlusion",
        "ischemic central retinal vein occlusion",
        "ischemic optic neuropathy",
        "lacquer crack",
        "lamellar macular hole",
        "large cup",
        "laser spots",
        "late dry age-related macular degeneration",
        "lattice degeneration",
        "leukemic retinopathy",
        "lipemia retinalis",
        "lymphoma",
        "macroaneurysm",
        "macula off retinal detachment",
        "macular atrophy",
        "macular dystrophy",
        "macular ectopia",
        "macular edema",
        "macular hemorrhage",
        "macular hole",
        "macular telangiectasia\u00a0",
        "maculopathy",
        "mass",
        "media opacity",
        "melanocytoma",
        "melanoma",
        "microaneurysm",
        "mild nonproliferative diabetic retinopathy",
        "moderate nonproliferative diabetic retinopathy",
        "morning glory syndrome",
        "multifocal choroiditis\u00a0",
        "multiple evanescent white dot syndrome",
        "multiple myeloma",
        "myelinated retinal nerve fiber layer",
        "myopia",
        "neoplasm",
        "neuroepithelial detachment",
        "neurofibromatosis",
        "neuroretinitis",
        "neuroretinopathy",
        "nonperfusion area",
        "nonproliferative diabetic retinopathy",
        "normal",
        "ocular candidiasis",
        "ocular histoplasmosis syndrome",
        "ocular ischemic syndrome",
        "ocular parasitosis",
        "ocular tuberculosis",
        "old retinal vein occlusion",
        "optic atrophy",
        "optic disc drusen",
        "optic disc edema",
        "optic disc melanocytoma",
        "optic disc neovascularization",
        "optic disc pallor",
        "optic disc pit",
        "optic nerve hypoplasia",
        "optic neuritis",
        "panuveitis",
        "papillitis",
        "pars plana vitrectomy",
        "patchy chorioretinal atrophy",
        "pathologic myopia",
        "pattern dystrophy",
        "perifoveal telangiectasia",
        "peripapillary atrophy",
        "pigmentary change",
        "plaquenil toxicity",
        "polypoidal choroidal vasculopathy",
        "polypoidal vascular abnormality ",
        "poor quality",
        "posterior uveitis",
        "posterior vitreous detachment",
        "preretinal hemorrhage",
        "presumed ocular histoplasmosis syndrome",
        "proliferative diabetic retinopathy",
        "proliferative vitreoretinopathy",
        "pseudopapilledema",
        "pseudoxanthoma elasticum",
        "punctate inner choroidopathy",
        "radiation retinopathy",
        "red small dots",
        "referable diabetic retinopathy",
        "retinal angiomatous proliferation",
        "retinal arterial macroaneurysm",
        "retinal artery occlusion",
        "retinal capillary hemangioblastoma",
        "retinal cavernous hemangioma",
        "retinal collateral",
        "retinal detachment",
        "retinal dystrophy",
        "retinal neovascularization",
        "retinal pigment epithelial detachment",
        "retinal pigment epithelial tears",
        "retinal pigment epithelium hamartoma",
        "retinal tear",
        "retinal telangiectasia",
        "retinal vein occlusion",
        "retinal vessel attenuation",
        "retinitis",
        "retinitis pigmentosa",
        "retinoblastoma",
        "retinopathy of prematurity",
        "retinoschisis",
        "rhegmatogenous retinal detachment",
        "roth spots",
        "sarcoidosis",
        "scar",
        "scleral band",
        "serous pigment epithelial detachment",
        "serous retinal detachment",
        "serpiginous choroiditis",
        "severe nonproliferative diabetic retinopathy",
        "sickle cell retinopathy",
        "silicone-oil-tamponade",
        "solar retinopathy",
        "staphyloma",
        "subhyaloid hemorrhage",
        "submacular hemorrhage",
        "subretinal exudate",
        "subretinal fibrosis",
        "subretinal hemorrhage",
        "sympathetic ophthalmia",
        "syphilis",
        "systemic lupus erythematosus vasculitis",
        "tessellation",
        "tortuous",
        "toxocariasis",
        "toxoplasmosis",
        "traction",
        "tractional retinal detachment",
        "tuberculosis",
        "uveitis",
        "valsalva retinopathy",
        "vascular hamartoma",
        "vascular sheath",
        "vasculitis",
        "venous loop",
        "viral retinitis",
        "vitelliform macular dystrophy",
        "vitreomacular traction syndrome",
        "vitreous degeneration",
        "vitreous hemorrhage",
        "vitreous opacity",
        "vitritis",
        "wet age-related macular degeneration",
        "white dot syndrome",
    ],
    "cfp_age": ["age"],
}

MULTIDIS_SIGNS = {
    "sign": [
        "siegrist streak",
        "preretinal hemorrhage",
        "retinal collateral",
        "optic disc hyperemia",
        "tilted disc",
        "aneurysm",
        "hyperpigmentation",
        "infarction",
        "focal atrophy",
        "cotton-wool spot",
        "angioid streak",
        "cherry-red spot ",
        "sub-internal limiting membrane hemorrhage",
        "atrophy",
        "optic disc pallor",
        "mass",
        "venous beading",
        "diffuse chorioretinal atrophy",
        "subretinal exudate",
        "macular infarction",
        "fuchs spot",
        "venous loop",
        "lattice degeneration",
        "hydrop",
        "vitreous degeneration",
        "ischemia",
        "hypopigmentation",
        "retinal vessel attenuation",
        "pigmentary change",
        "tessellation",
        "hypertrophy of the RPE",
        "posterior vitreous detachment",
        "arteriovenous shunts",
        "hyperplasia of the RPE",
        "choroidal folds",
        "sub-RPE hemorrhage",
        "nerve fiber layer hemorrhage",
        "arterial-venous nicking",
        "macular atrophy",
        "drusen",
        "traction",
        "massive hemorrhage",
        "soft drusen",
        "fleck",
        "polypoidal vascular abnormality ",
        "chorioretinal atrophy",
        "arteriosclerosis",
        "subretinal hemorrhage",
        "peripapillary atrophy",
        "nonperfusion area",
        "macular hemorrhage",
        "retinal neovascularization",
        "intraretinal hemorrhage",
        "intraretinal microvascular abnormalities",
        "choroidal rupture",
        "outer retinal tubulation",
        "optic disc neovascularization",
        "hollenhorst plaque",
        "microaneurysm",
        "optic disc atrophy",
        "branching vascular network",
        "submacular hemorrhage",
        "large cup",
        "vitreous opacity",
        "hemorrhage",
        "bone spicules pigmentation",
        "hypopyon",
        "cystic retinal tuft",
        "macroaneurysm",
        "ghost vessel",
        "Dalen\u2013Fuchs nodules",
        "pseudopapilledema",
        "red small dots",
        "prepapillary membrane",
        "weiss ring",
        "vascular sheath",
        "tortuous",
        "exudate",
        "optic disc edema",
        "choroidal infarction",
        "roth spots",
        "patchy chorioretinal atrophy",
        "hard drusen",
        "edema",
        "lacquer crack",
        "asteroid bodies",
        "crystalline deposits",
        "fibroproliferation",
    ],
}

DEFAULT_SHOW_N = {"multidis": 5, "cfp_quality": 3, "modality": 3, "laterality": 1, "cfp_age": 1}

__all__ = ["TASK_CLASS_MAP", "MULTIDIS_SIGNS", "DEFAULT_SHOW_N"]