# Global EyeAgent configuration
llm:
  default:
    base_url: https://api.deepseek.com/v1
    model: deepseek-chat
    temperature: 0.7
    max_tokens: 4096
  agents:
    # Example overrides per agent class name
    # OrchestratorAgent:
    #   model: deepseek-chat
    #   temperature: 0.5
    # ReportAgent:
    #   model: gpt-4o-mini

workflow:
  # unified | graph | interaction | profile
  mode: unified

agents:
  unified:
    class: eyeagent.agents.unified_agent.UnifiedAgent
    enabled: true

# Optional per-agent tool filters (regex lists)
tools_filter:
  UnifiedAgent:
    include: [".*"]
