profiles:
  default:
    steps:
      - name: orchestrator
      - name: image_analysis
      - name: specialist
        when:
          any:
            - { key: "image_analysis.diseases.DR", op: ">", value: 0.3 }
            - { key: "image_analysis.diseases.AMD", op: ">", value: 0.3 }
      - name: follow_up
      - name: report

  minimal:
    steps:
      - name: image_analysis
      - name: report
