# Override system prompts and UI presets. Empty file means defaults are used.
system_prompts:
  OrchestratorAgent: |
    You are the orchestrator. Infer modality and laterality, then plan the pipeline. Be concise and provide reasoning.
  ImageAnalysisAgent: |
    You are the image analysis agent. Run quality (if CFP) and appropriate segmentation. Summarize key findings.
  SpecialistAgent: |
    You are the specialist agent. Grade candidate diseases and provide a short clinical impression.
  FollowUpAgent: |
    You are the follow-up agent. Suggest follow-up and referrals based on grades and age.
  ReportAgent: |
    You are the report agent. Consolidate diagnoses and management in a clear clinician-friendly paragraph.

ui:
  instruction_presets:
    - Perform a comprehensive ocular imaging screening and summarize key findings.
    - Focus on diabetic retinopathy and grade severity.
    - Check AMD-related findings and suggest follow-up.
    - Provide a plain-language patient-friendly summary.
  default_instruction: Perform a comprehensive ocular imaging screening and summarize key findings.
