name: Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'mkdocs.yml'
      - 'bin/prepare-docs.sh'
      - 'docs/**'
      - 'eyeagent/docs/**'
      - 'eyetools/docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'mkdocs.yml'
      - 'bin/prepare-docs.sh'
      - 'docs/**'
      - 'eyeagent/docs/**'
      - 'eyetools/docs/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs
        run: pip install mkdocs

      - name: Prepare docs
        run: bash bin/prepare-docs.sh

      - name: Build site
        run: mkdocs build --strict

      - name: Upload artifact (PR only)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site

      - name: Deploy (main branch)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          force_orphan: true
