name: Publish Python Packages

on:
  push:
    tags:
      - 'eyetools-v*'
      - 'eyeagent-v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-eyetools:
    if: startsWith(github.ref_name, 'eyetools-v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build backend
        run: pip install --upgrade build

      - name: Derive version from tag & validate pyproject
        id: ver
        working-directory: eyetools
        run: |
          TAG='${{ github.ref_name }}'
          PREFIX='eyetools-v'
          VERSION="${TAG#${PREFIX}}"
          echo "Tag: $TAG -> Version: $VERSION"
          FILE_VERSION=$(grep '^version *= *' pyproject.toml | head -n1 | sed -E "s/version *= *\"([^\"]+)\"/\1/")
          echo "pyproject.toml version: $FILE_VERSION"
          if [ "$VERSION" != "$FILE_VERSION" ]; then
            echo "::error::Tag version ($VERSION) does not match pyproject.toml version ($FILE_VERSION)" >&2
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build wheel & sdist
        working-directory: eyetools
        run: python -m build --wheel --sdist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN_EYEAGENT }}
          packages-dir: eyetools/dist
          verbose: true

      - name: Summary
        run: echo "Published eyetools version ${{ steps.ver.outputs.version }}" >> $GITHUB_STEP_SUMMARY

  publish-eyeagent:
    if: startsWith(github.ref_name, 'eyeagent-v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build backend
        run: pip install --upgrade build

      - name: Derive version from tag & validate pyproject
        id: ver
        working-directory: eyeagent
        run: |
          TAG='${{ github.ref_name }}'
          PREFIX='eyeagent-v'
          VERSION="${TAG#${PREFIX}}"
          echo "Tag: $TAG -> Version: $VERSION"
          FILE_VERSION=$(grep '^version *= *' pyproject.toml | head -n1 | sed -E "s/version *= *\"([^\"]+)\"/\1/")
          echo "pyproject.toml version: $FILE_VERSION"
          if [ "$VERSION" != "$FILE_VERSION" ]; then
            echo "::error::Tag version ($VERSION) does not match pyproject.toml version ($FILE_VERSION)" >&2
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build wheel & sdist
        working-directory: eyeagent
        run: python -m build --wheel --sdist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN_EYEAGENT }}
          packages-dir: eyeagent/dist
          verbose: true

      - name: Summary
        run: echo "Published eyeagent version ${{ steps.ver.outputs.version }}" >> $GITHUB_STEP_SUMMARY
